### ISSUE TITLE
recv 및 recv_data의 return 값 확인

### ISSUE THREAD

**Issue by snoopspy** [qudwns2052/NetKillerW_SA#1]
recv의 return 값이 0인 경우는 소켓 연결이 close되었다는 것을 의미함. 참고하세요,
https://stackoverflow.com/questions/3091010/recv-socket-function-returning-data-with-length-as-0/3091039#:~:text=When%20recv%20returns%20a%20value,has%20performed%20an%20orderly%20shutdown.

https://github.com/qudwns2052/NetKillerW_SA/commit/6cc20e9c5c9595f0a7e26fd616feb6abcb4b30a9#r44725321

https://github.com/qudwns2052/NetKillerW_SA/commit/aedccabbc6f27e5dc5261a660de0a2b23f238a68#r44725360

https://github.com/qudwns2052/NetKillerW_SA/commit/aedccabbc6f27e5dc5261a660de0a2b23f238a68#r44725376

**Comment by qudwns2052** [comment]
Done
