### ISSUE TITLE
hopping_func 무한루프에서 sleep을 하지 않는 문제점.

### ISSUE THREAD

**Issue by snoopspy** [qudwns2052/NetKillerW_SA#2]
https://github.com/qudwns2052/NetKillerW_SA/blob/885e596834325be59eafd01fa97ac2ab3739115c/main.cpp
void hopping_func()을 보면  hopping_active가 false일 때 sleep 없이 무한루프를 돌게 되어 있음.
가끔 프로그램을 실행시키면 스마트폰 발열이 생기는데 이 문제 아닌가 생각됨.

**Comment by qudwns2052** [comment]
won't fix

**Comment by qudwns2052** [comment]
Done in 03f23172d4ad34d7cd79470f257219a0a6efdbd0
